image: docker:24

services:
  - name: docker:dind
    alias: docker

stages:
  - lint
  - test

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

lint:
  stage: lint
  script:
    - make lint

molecule_test:
  stage: test
  script:
    - make run-test-ci
  parallel:
    matrix:
      - ANSIBLE_VERSION: ["8"]
        MOLECULE_DOCKER_VERSION: ["24.0.0"]
        MOLECULE_SCENARIO: ["debian", "oraclelinux"]
