image: docker:stable

services:
  - name: docker:dind-stable
    alias: docker

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build_image:
  stage: build
  script:
    - make target=build pull
    - make target=build build
    - make target=build push

molecule_test:
  stage: test
  script:
    - make target=build test
