version: "3.8"

services:
  molecule:
    build:
      context: molecule
      target: molecule
      args:
        PYTHON_BASE_IMAGE_VERSION: ${PYTHON_BASE_IMAGE_VERSION:-3.11}
        ANSIBLE_VERSION: ${ANSIBLE_VERSION:-6.7}
        ANSIBLE_LINT_VERSION: ${ANSIBLE_LINT_VERSION:-v6.12}
        MOLECULE_VERSION: ${MOLECULE_VERSION:-5.1}
        MOLECULE_DOCKER_PLUGIN_VERESION: ${MOLECULE_DOCKER_PLUGIN_VERESION:-23.0}
        DOCKER_VERSION: ${DOCKER_VERSION:-23}
        BUILDKIT_INLINE_CACHE: ${BUILDKIT_INLINE_CACHE:-1}
    working_dir: /developed_role
    command: molecule test
    volumes:
      - ./:/developed_role
      - /var/run/docker.sock:/var/run/docker.sock
