version: "3.8"

services:
  molecule:
    build:
      cache_from:
        - ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${CI_COMMIT_REF_NAME}
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/molecule:${CI_COMMIT_REF_NAME}
