- name: debian-11 | Install docker dependencies
  ansible.builtin.apt:
    update_cache: "{{ role_docker_update_package_manager_cache | bool }}"
    pkg:
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - lsb-release
      - libffi-dev
      - pkg-config
  notify: "cleanup packages"

- name: debian-11 | Install docker v{{ role_docker_version }}
  ansible.builtin.apt:
    update_cache: "{{ role_docker_update_package_manager_cache | bool }}"
    force: true
    allow_downgrade: true
    pkg:
      - "docker-ce=5:{{ role_docker_version }}-1~{{ ansible_distribution | lower }}.{{ ansible_distribution_major_version }}~\
         {{ ansible_distribution_release }}"
      - "docker-ce-cli=5:{{ role_docker_version }}-1~{{ ansible_distribution | lower }}.{{ ansible_distribution_major_version }}~\
         {{ ansible_distribution_release }}"
  notify:
    - "restart docker service"
    - "cleanup packages"

- name: debian-11 | Prevent docker-ce from being upgraded
  tags: configure
  ansible.builtin.dpkg_selections:
    name: docker-ce
    selection: hold

- name: debian-11 | Prevent docker-ce-cli from being upgraded
  tags: configure
  ansible.builtin.dpkg_selections:
    name: docker-ce-cli
    selection: hold
