- name: add an apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add docker source repository into sources list
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: install docker dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - containerd.io
      - lsb-release
      - libffi-dev
      - python3-pip
      - python-setuptools
      - python3-setuptools
      - pkg-config
      - python3-dev
  notify: "cleanup packages"

- name: install docker v{{ role_docker_version }}
  ansible.builtin.apt:
    update_cache: true
    force: true
    allow_downgrade: true
    pkg:
      - docker-ce=5:{{ role_docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
      - docker-ce-cli=5:{{ role_docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}
  notify:
    - "enable docker service"
    - "restart docker service"
    - "cleanup packages"

- name: prevent docker-ce from being upgraded
  tags: configure
  ansible.builtin.dpkg_selections:
    name: docker-ce
    selection: hold

- name: prevent docker-ce-cli from being upgraded
  tags: configure
  ansible.builtin.dpkg_selections:
    name: docker-ce-cli
    selection: hold
