- name: Centos extras
  ansible.builtin.yum_repository:
    name: centos-extras
    description: Centos extras - $basearch
    file: centos-extras
    baseurl: http://mirror.centos.org/centos/7/extras/$basearch/
    gpgcheck: true
    gpgkey: http://centos.org/keys/RPM-GPG-KEY-CentOS-7

- name: enable Oracle repo addons
  ansible.builtin.yum_repository:
    name: addons-ol7
    description: "Some dependence for docker"
    baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/
    gpgcheck: true
    gpgkey: http://yum.oracle.com/RPM-GPG-KEY-oracle-ol7
    enabled: false

- name: add docker-ce-stable repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker dependencies
  ansible.builtin.yum:
    update_cache: true
    state: latest
    name:
      - containerd.io
      - docker-compose-plugin
  notify: "cleanup packages"

- name: install docker v{{ role_docker_version }}
  ansible.builtin.yum:
    update_cache: true
    allow_downgrade: true
    name:
      - docker-ce-{{ role_docker_version }}
      - docker-ce-cli-{{ role_docker_version }}
  notify:
    - "enable docker service"
    - "restart docker service"
    - "cleanup packages"

- name: prevent docker-ce and docker-ce-cli from being upgraded
  tags: fix_version
  community.general.yum_versionlock:
    state: present
    name:
      - docker-ce-{{ role_docker_version }}
      - docker-ce-cli-{{ role_docker_version }}
