- name: _service | Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: _service | Start docker service
  ansible.builtin.service:
    name: docker
    state: started

- name: _service | Wait for Docker service
  ansible.builtin.service_facts:
  register: _services_facts
  until: >-
    _services_facts.ansible_facts.services['docker.service'] is defined and
    _services_facts.ansible_facts.services['docker.service'].state == "running"
  retries: "{{ role_docker_as_service_check_retries }}"
  delay: "{{ role_docker_as_service_check_delay }}"
  when: role_docker_as_service_check_started
