- name: Cleanup default docker packages
  tags: cleanup
  ansible.builtin.include_tasks: cleanup/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml

- name: Prepare python and environment
  tags: prepare
  ansible.builtin.include_tasks: prepare/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml

- name: Prepare OS
  tags: prepare
  ansible.builtin.import_tasks: os-prepare.yml

- name: Add official docker repositories
  tags: prepare,repos
  when: role_docker_add_official_docker_repos
  ansible.builtin.include_tasks: repos/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml

- name: Install docker
  tags: install
  ansible.builtin.include_tasks: install/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml

- name: Set docker daemon.json
  tags: configure
  ansible.builtin.import_tasks: configure/daemon.json.yml

- name: Install docker-compose
  tags: install, compose
  ansible.builtin.import_tasks: install/compose.yml

- name: Post tasks
  tags: install
  when: role_docker_as_service
  ansible.builtin.include_tasks: post_tasks/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml
