- name: os-prepare | Ensures that directory for docker config exists | {{ role_docker_config_dir_path }}
  tags: install,config
  ansible.builtin.file:
    path: "{{ role_docker_config_dir_path }}"
    state: directory
    mode: "{{ role_docker_config_dir_mode }}"
  when: role_docker_config_dir_path is defined and
        role_docker_config_dir_path | length > 0 and
        role_docker_config_dir_mode is defined and
        role_docker_config_dir_mode | length > 0

- name: os-prepare | Ensures that directory for docker data exists | {{ role_docker_data_dir_path }}
  tags: install,config
  ansible.builtin.file:
    path: "{{ role_docker_data_dir_path }}"
    state: directory
    mode: "{{ role_docker_data_dir_mode }}"
  when: role_docker_data_dir_path is defined and
        role_docker_data_dir_path | length > 0 and
        role_docker_data_dir_mode is defined and
        role_docker_data_dir_mode | length > 0
