- name: oraclelinux-8 | Add docker-ce-stable repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
