- name: oraclelinux-7 | Centos extras
  ansible.builtin.yum_repository:
    name: centos-extras
    description: Centos extras - $basearch
    file: centos-extras
    baseurl: http://mirror.centos.org/centos/7/extras/$basearch/
    gpgcheck: true
    gpgkey: http://centos.org/keys/RPM-GPG-KEY-CentOS-7

- name: oraclelinux-7 | Enable Oracle repo addons
  ansible.builtin.yum_repository:
    name: addons-ol7
    description: "Some dependence for docker"
    baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/
    gpgcheck: true
    gpgkey: http://yum.oracle.com/RPM-GPG-KEY-oracle-ol7
    enabled: false

- name: oraclelinux-7 | Add docker-ce-stable repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
