- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted
  listen: "restart docker service"
  when: role_docker_as_service | bool

- name: Cleanup apt packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  listen: "cleanup packages"
  when: "ansible_distribution in ('Debian', 'Ubuntu')"

- name: Cleanup yum packages
  ansible.builtin.command: yum clean all
  listen: "cleanup packages"
  when: "ansible_distribution in ('OracleLinux', 'RedHat')"
  changed_when: false
