{% if item.registry is defined %}
    FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
  FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
  {% for var, value in item.env.items() %}
    {% if value %}
      ENV {{ var }} {{ value }}
    {% endif %}
  {% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then \
		apt-get update && apt-get install -y sudo bash ca-certificates cron gpg nginx systemd systemd-sysv curl vim python3 python3-apt python3-pip python3-setuptools && apt-get clean; \
    elif [ $(command -v dnf) ]; then \
		dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash && dnf clean all; \
    {# elif [ $(command -v yum) ]; then \
		yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \ #}
    elif [ $(command -v apk) ]; then \
		apk update && apk add --no-cache python sudo bash ca-certificates; \
	fi
