---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: debian:bullseye
    pre_build_image: false
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint .
verifier:
  name: ansible
