{% if item.registry is defined %}
    FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
  FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
  {% for var, value in item.env.items() %}
    {% if value %}
      ENV {{ var }} {{ value }}
    {% endif %}
  {% endfor %}
{% endif %}

RUN apt-get update && \
    apt-get install -y sudo python3 python3-pip python3-setuptools ca-certificates systemd systemd-sysv && \
    apt-get clean
